### ISSUE TITLE
Win10 64位 java.lang.UnsatisfiedLinkError: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by 1b1og-com** [anhkgg/SuperWeChatPC#102]
hello java WechatSDK
Exception in thread "main" java.lang.UnsatisfiedLinkError: %1 不是有效的 Win32 应用程序。

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:278)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:646)
	at com.sun.jna.Native.loadLibrary(Native.java:630)
	at net.n9o.WeChatSDK.<clinit>(WeChatSDK.java:10)
	at net.n9o.TestJavaSDK.main(TestJavaSDK.java:11)

**Comment by geekyouth** [comment]
同问

**Comment by jiuaiwo** [comment]
同问
