### ISSUE TITLE
大佬，我使用Py调试的时候显示不是32位应用程序

### ISSUE THREAD

**Issue by qsws3344** [anhkgg/SuperWeChatPC#25]
Traceback (most recent call last):
  File "WeChatSDK.py", line 55, in <module>
    wxsdk = WXSDK()
  File "WeChatSDK.py", line 8, in __init__
    self.sdk = ctypes.CDLL("WeChatSDK.dll")
  File "C:\Users\qsws3\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by anhkgg** [comment]
安装python x86版本的

**Comment by qsws3344** [comment]
> 安装python x86版本的

这个问题已经解决，回调接收消息接口。自己发送出去的消息也会被回调到，没办法区分是对方的消息还是自己的消息！如果可以提供message的ID应该是可以解决这个问题

**Comment by zane0113** [comment]
请问python 回调怎么写，我写了回调没有出现错误，返回是0，就退出了，无法实时显示收到的消息，回调部分源码能分享下吗
